[InputPanel]
HighlightCandidateColor=#000000

[InputPanel/Highlight]
Image=
Color=#00000000
BorderColor=#00000000
BorderWidth=0

[Menu]
HighlightCandidateColor=#000000

[Menu/Highlight]
Image=
Color=#00000000
BorderColor=#00000000
BorderWidth=0
